Update patch set 1
Patch Set 1:

getting since last week - upgrade/install ambiguity - fixed by an empty helm install first 
ubuntu@ip-172-31-29-61:~/oom/kubernetes$ sudo helm deploy onap local/onap --namespace onap -f ../../dev.yaml --verbose
fetching local/onap
Error: UPGRADE FAILED: "onap-dmaap" has no deployed releases
Error: UPGRADE FAILED: "onap-log" has no deployed releases
Error: UPGRADE FAILED: "onap-pomba" has no deployed releases
Error: UPGRADE FAILED: "onap-robot" has no deployed releases
onap-dmaap	1       	Thu Dec 27 00:46:47 2018	FAILED  	dmaap-3.0.0	onap     
onap-log  	1       	Thu Dec 27 00:46:49 2018	FAILED  	log-3.0.0  	onap     
onap-pomba	1       	Thu Dec 27 00:46:51 2018	FAILED  	pomba-3.0.0	onap     
onap-robot	1       	Thu Dec 27 00:46:54 2018	FAILED  	robot-3.0.0	onap     

fixed by an empty deploy first
sudo helm deploy onap local/onap --namespace onap -f onap/resources/environments/disable-allcharts.yaml --verbose
sudo helm deploy onap local/onap --namespace onap -f ../../dev.yaml --verbose
ubuntu@ip-172-31-29-61:~/oom/kubernetes$ sudo helm list
NAME      	REVISION	UPDATED                 	STATUS  	CHART      	NAMESPACE
onap      	2       	Thu Dec 27 01:06:12 2018	DEPLOYED	onap-3.0.0 	onap     
onap-dmaap	1       	Thu Dec 27 01:06:14 2018	DEPLOYED	dmaap-3.0.0	onap     
onap-log  	1       	Thu Dec 27 01:06:18 2018	DEPLOYED	log-3.0.0  	onap     
onap-pomba	1       	Thu Dec 27 01:06:26 2018	DEPLOYED	pomba-3.0.0	onap     
onap-robot	1       	Thu Dec 27 01:06:38 2018	DEPLOYED	robot-3.0.0	onap

Patch-set: 1
Label: Code-Review=0