Update patch set 2
Patch Set 2:

test results - notice the rogue pod that was deleted

ubuntu@a-cd-cas0:~$ sudo nohup ./cd.sh -b 3.0.0-ONAP -e onap -p true -n nexus3.onap.cloud:5000 -f true -s 300 -c true -d true -w false -r false &
[1] 24353
ubuntu@a-cd-cas0:~$ nohup: ignoring input and appending output to 'nohup.out'

ubuntu@a-cd-cas0:~$ sudo tail -f nohup.out 
waiting for deletions to complete, iterations left: 27
waiting for deletions to complete, iterations left: 26
Tue Jan 15 19:23:53 UTC 2019
running with: -b 3.0.0-ONAP -e onap -p true -n nexus3.onap.cloud:5000 -f true -s 300 -c true -d true -w false -r 
provide onap-parameters.yaml(amsterdam) or dev0.yaml+dev1.yaml (master) and aai-cloud-region-put.json
provide a dev0.yaml and dev1.yaml override (0=platform, 1=rest of pods) - copy from https://git.onap.org/oom/tree/kubernetes/onap/resources/environments/dev.yaml
vm.max_map_count = 262144
remove currently deployed pods
Error from server (Conflict): Operation cannot be fulfilled on namespaces "onap": The system is ensuring all content is removed from this namespace.  Upon completion, this namespace will automatically be purged by the system.
sleep for 4 min to allow the delete to finish pod terminations before trying a helm delete
Error: release: "onap" not found
showing 1 undeleted pods
onap-oof-oof-has-reservation-5cd655b79f-56cn7   0/1       Terminating   0          15d
verify deletion is finished.
waiting for deletions to complete, iterations left: 40
waiting for deletions to complete, iterations left: 39
^C
ubuntu@a-cd-cas0:~$ kubectl get pods --all-namespaces
NAMESPACE     NAME                                            READY     STATUS        RESTARTS   AGE
kube-system   heapster-7b48b696fc-j4x45                       1/1       Running       0          16d
kube-system   kube-dns-6655f78c68-zdxsd                       3/3       Running       3          16d
kube-system   kubernetes-dashboard-6f54f7c4b-7kpwf            1/1       Running       0          16d
kube-system   monitoring-grafana-7877679464-f8j56             1/1       Running       0          16d
kube-system   monitoring-influxdb-64664c6cf5-5hqnt            1/1       Running       0          16d
kube-system   tiller-deploy-6f4745cbcf-cdmzl                  1/1       Running       0          16d
onap          onap-oof-oof-has-reservation-5cd655b79f-56cn7   0/1       Terminating   0          15d
ubuntu@a-cd-cas0:~$ sudo tail -f nohup.out 
remove currently deployed pods
Error from server (Conflict): Operation cannot be fulfilled on namespaces "onap": The system is ensuring all content is removed from this namespace.  Upon completion, this namespace will automatically be purged by the system.
sleep for 4 min to allow the delete to finish pod terminations before trying a helm delete
Error: release: "onap" not found
showing 1 undeleted pods
onap-oof-oof-has-reservation-5cd655b79f-56cn7   0/1       Terminating   0          15d
verify deletion is finished.
waiting for deletions to complete, iterations left: 40
waiting for deletions to complete, iterations left: 39
waiting for deletions to complete, iterations left: 38
waiting for deletions to complete, iterations left: 37
waiting for deletions to complete, iterations left: 36
waiting for deletions to complete, iterations left: 35
waiting for deletions to complete, iterations left: 34
waiting for deletions to complete, iterations left: 33
waiting for deletions to complete, iterations left: 32
waiting for deletions to complete, iterations left: 31
waiting for deletions to complete, iterations left: 30
waiting for deletions to complete, iterations left: 29
waiting for deletions to complete, iterations left: 28
waiting for deletions to complete, iterations left: 27
waiting for deletions to complete, iterations left: 26
waiting for deletions to complete, iterations left: 25
waiting for deletions to complete, iterations left: 24
waiting for deletions to complete, iterations left: 23
waiting for deletions to complete, iterations left: 22
waiting for deletions to complete, iterations left: 21
waiting for deletions to complete, iterations left: 20
waiting for deletions to complete, iterations left: 19
waiting for deletions to complete, iterations left: 18
waiting for deletions to complete, iterations left: 17
waiting for deletions to complete, iterations left: 16
waiting for deletions to complete, iterations left: 15
waiting for deletions to complete, iterations left: 14
waiting for deletions to complete, iterations left: 13
waiting for deletions to complete, iterations left: 12
waiting for deletions to complete, iterations left: 11
waiting for deletions to complete, iterations left: 10
waiting for deletions to complete, iterations left: 9
waiting for deletions to complete, iterations left: 8
waiting for deletions to complete, iterations left: 7
waiting for deletions to complete, iterations left: 6
waiting for deletions to complete, iterations left: 5
waiting for deletions to complete, iterations left: 4
waiting for deletions to complete, iterations left: 3
waiting for deletions to complete, iterations left: 2
waiting for deletions to complete, iterations left: 1
--force delete on pods: onap-oof-oof-has-reservation-5cd655b79f-56cn7
running: kubectl delete pods onap-oof-oof-has-reservation-5cd655b79f-56cn7 --grace-period=0 --force -n onap
warning: Immediate deletion does not wait for confirmation that the running resource has been terminated. The resource may continue to run on the cluster indefinitely.
pod "onap-oof-oof-has-reservation-5cd655b79f-56cn7" force deleted
No resources found.
Pod deletions completed
No resources found
No resources found
secret "default-token-lvrvf" deleted
No resources found
^C
ubuntu@a-cd-cas0:~$ kubectl get pods --all-namespaces
NAMESPACE     NAME                                   READY     STATUS    RESTARTS   AGE
kube-system   heapster-7b48b696fc-j4x45              1/1       Running   0          16d
kube-system   kube-dns-6655f78c68-zdxsd              3/3       Running   3          16d
kube-system   kubernetes-dashboard-6f54f7c4b-7kpwf   1/1       Running   0          16d
kube-system   monitoring-grafana-7877679464-f8j56    1/1       Running   0          16d
kube-system   monitoring-influxdb-64664c6cf5-5hqnt   1/1       Running   0          16d
kube-system   tiller-deploy-6f4745cbcf-cdmzl         1/1       Running   0          16d
ubuntu@a-cd-cas0:~$ sudo tail -f nohup.out 
NAMESPACE     NAME                                   READY     STATUS    RESTARTS   AGE       IP              NODE                                                            NOMINATED NODE
kube-system   heapster-7b48b696fc-j4x45              1/1       Running   0          16d       10.42.70.33     a-cd-cas0.5hiifda2ndue3bsfctongqv1sb.cx.internal.cloudapp.net   <none>
kube-system   kube-dns-6655f78c68-zdxsd              3/3       Running   3          16d       10.42.71.131    a-cd-cas0.5hiifda2ndue3bsfctongqv1sb.cx.internal.cloudapp.net   <none>
kube-system   kubernetes-dashboard-6f54f7c4b-7kpwf   1/1       Running   0          16d       10.42.42.227    a-cd-cas0.5hiifda2ndue3bsfctongqv1sb.cx.internal.cloudapp.net   <none>
kube-system   monitoring-grafana-7877679464-f8j56    1/1       Running   0          16d       10.42.121.31    a-cd-cas0.5hiifda2ndue3bsfctongqv1sb.cx.internal.cloudapp.net   <none>
kube-system   monitoring-influxdb-64664c6cf5-5hqnt   1/1       Running   0          16d       10.42.1.239     a-cd-cas0.5hiifda2ndue3bsfctongqv1sb.cx.internal.cloudapp.net   <none>
kube-system   tiller-deploy-6f4745cbcf-cdmzl         1/1       Running   0          16d       10.42.138.226   a-cd-cas0.5hiifda2ndue3bsfctongqv1sb.cx.internal.cloudapp.net   <none>
 deleting /dockerdata-nfs/ all onap-* deployment directories - why: some pod config jobs will not run on a non-empty nfs subdir
pull new oom
Cloning into 'oom'...

Patch-set: 2